# 💸 Apoya a Ulert

**Ulert** es una herramienta open source gratuita, creada y mantenida por [u-site.app](https://u-site.app) con el objetivo de ayudar a desarrolladores, empresas y creadores a mantener sus sitios web saludables, seguros y funcionales.

Si usas Ulert en tu proyecto, empresa o como parte de tu flujo de trabajo, considera hacer una contribución para ayudarnos a seguir mejorando esta herramienta.

Cada aporte, grande o pequeño, nos ayuda a:
- Corregir bugs y mejorar la estabilidad
- Añadir nuevas funciones (como alertas por Discord, dashboard, CI/CD)
- Mantener la documentación actualizada
- Responder a la comunidad y guiar a nuevos contribuidores

---

## 🏦 Cómo donar

Actualmente aceptamos contribuciones a través de:

### 🟡 GitHub Sponsors
Haz una donación mensual a través de GitHub:
👉 [github.com/sponsors/u-site-sas-bic](https://github.com/sponsors/u-site-sas-bic)  
(Próximamente habilitado — mantente atento)

### 💳 Open Collective
Donaciones únicas o recurrentes vía tarjeta o PayPal:
👉 [opencollective.com/usite](https://opencollective.com/usite)  
(En configuración — contacto: info@u-site.app)

### ⚙️ Patrocinios corporativos
¿Tu empresa usa Ulert en producción?  
Ofrecemos opciones de **patrocinio oficial** con reconocimiento en:
- README.md
- Sitio web (`u-site.app`)
- Comunicados de prensa

📧 Contáctanos: **info@u-site.app**

---

## 🙌 Reconocimiento a patrocinadores

Agradecemos especialmente a quienes apoyan el desarrollo de software ético y abierto.

| Tipo | Nombre | Nivel | Enlace |
|------|--------|-------|--------|
| 🏢 Próximamente | Tu empresa aquí | Sponsor oficial | [tu-sitio.com](https://tu-sitio.com) |
| 👤 Próximamente | Tu nombre aquí | Donante destacado | — |

> ¿Quieres aparecer aquí? Haz una contribución hoy.

---

## 📢 ¿Por qué donar?

Ulert es:
- 🔒 100% privado: no rastrea ni envía datos a terceros
- 📦 Auto-hospedable: puedes ejecutarlo en tu infraestructura
- 📚 Open source: código abierto bajo licencia MIT
- 🌍 Útil: audita, monitorea y protege cualquier sitio web

Con tu apoyo, podemos hacer de Ulert una herramienta aún más poderosa para toda la comunidad.

---

> Hecho con ❤️ por [u-site.app](https://u-site.app) — Software funcional, ético y centrado en el usuario.